

export const plans = [
  {
    name: "Shared Hosting",
    tag: "Starter",
    price: "৳299",
    period: "/month",
    description: "Perfect for small websites, blogs, and startups just getting started.",
    popular: false,
    features: [
      "5 GB SSD Storage",
      "1 Website",
      "Free SSL Certificate",
      "10 Email Accounts",
      "99.9% Uptime SLA",
      "Daily Backups",
      "cPanel Access",
      "24/7 Support",
    ],
    cta: "Get Started",
    href: "/contact",
  },
  {
    name: "VPS Hosting",
    tag: "Most Popular",
    price: "৳1,499",
    period: "/month",
    description: "Full control with dedicated resources. Ideal for growing businesses.",
    popular: true,
    features: [
      "50 GB SSD Storage",
      "Unlimited Websites",
      "Free SSL Certificate",
      "Unlimited Email Accounts",
      "99.9% Uptime SLA",
      "Daily Backups",
      "Root Access",
      "Dedicated IP",
      "24/7 Priority Support",
      "Custom Software Install",
    ],
    cta: "Get Started",
    href: "/contact",
  },
  {
    name: "Dedicated Server",
    tag: "Heavy Load",
    price: "৳7,999",
    period: "/month",
    description: "Maximum performance and security for high-traffic enterprise applications.",
    popular: false,
    features: [
      "1 TB SSD Storage",
      "Unlimited Websites",
      "Free SSL Certificate",
      "Unlimited Email Accounts",
      "99.99% Uptime SLA",
      "Hourly Backups",
      "Full Root Access",
      "Dedicated IP",
      "DDoS Protection",
      "24/7 Priority Support",
      "Hardware Management",
    ],
    cta: "Get Started",
    href: "/contact",
  },
  {
    name: "Reseller Hosting",
    tag: "For Agencies",
    price: "৳2,499",
    period: "/month",
    description: "Start your own hosting business. Sell hosting under your own brand.",
    popular: false,
    features: [
      "100 GB SSD Storage",
      "Unlimited Websites",
      "Free SSL Certificate",
      "WHM Control Panel",
      "White Label Branding",
      "Create Client Accounts",
      "99.9% Uptime SLA",
      "Daily Backups",
      "24/7 Support",
    ],
    cta: "Get Started",
    href: "/contact",
  },
];


export const comparisonFeatures = [
  { feature: "SSD Storage", shared: "5 GB", vps: "50 GB", dedicated: "1 TB", reseller: "100 GB" },
  { feature: "Websites", shared: "1", vps: "Unlimited", dedicated: "Unlimited", reseller: "Unlimited" },
  { feature: "Email Accounts", shared: "10", vps: "Unlimited", dedicated: "Unlimited", reseller: "Unlimited" },
  { feature: "Free SSL", shared: "✓", vps: "✓", dedicated: "✓", reseller: "✓" },
  { feature: "Daily Backups", shared: "✓", vps: "✓", dedicated: "Hourly", reseller: "✓" },
  { feature: "Root Access", shared: "✗", vps: "✓", dedicated: "✓", reseller: "✗" },
  { feature: "Dedicated IP", shared: "✗", vps: "✓", dedicated: "✓", reseller: "✗" },
  { feature: "White Label", shared: "✗", vps: "✗", dedicated: "✗", reseller: "✓" },
  { feature: "DDoS Protection", shared: "✗", vps: "✗", dedicated: "✓", reseller: "✗" },
  { feature: "Uptime SLA", shared: "99.9%", vps: "99.9%", dedicated: "99.99%", reseller: "99.9%" },
];
